/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const BlogArticle = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const Pet = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'shelterName' : IDL.Text,
  'healthStatus' : IDL.Text,
  'available' : IDL.Bool,
  'gender' : IDL.Text,
  'shelterId' : IDL.Text,
  'shelterEmail' : IDL.Text,
  'breed' : IDL.Text,
  'species' : IDL.Text,
  'location' : IDL.Text,
  'photos' : IDL.Vec(IDL.Text),
  'vaccinationStatus' : IDL.Text,
  'shelterPhone' : IDL.Text,
});
export const AdoptionApplication = IDL.Record({
  'id' : IDL.Text,
  'zip' : IDL.Text,
  'applicantName' : IDL.Text,
  'homeType' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'experience' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'petId' : IDL.Nat,
  'phone' : IDL.Text,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  'applyToFoster' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getBlogArticle' : IDL.Func([IDL.Nat], [IDL.Opt(BlogArticle)], ['query']),
  'getFeaturedPets' : IDL.Func([], [IDL.Vec(Pet)], ['query']),
  'getPet' : IDL.Func([IDL.Nat], [IDL.Opt(Pet)], ['query']),
  'listAdoptionApplications' : IDL.Func([], [IDL.Vec(AdoptionApplication)], []),
  'listBlogArticles' : IDL.Func([], [IDL.Vec(BlogArticle)], ['query']),
  'listPets' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(Pet)],
      ['query'],
    ),
  'registerVolunteer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Text],
      [],
    ),
  'sendContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'setAdmin' : IDL.Func([], [IDL.Text], []),
  'submitAdoptionApplication' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const BlogArticle = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const Pet = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'shelterName' : IDL.Text,
    'healthStatus' : IDL.Text,
    'available' : IDL.Bool,
    'gender' : IDL.Text,
    'shelterId' : IDL.Text,
    'shelterEmail' : IDL.Text,
    'breed' : IDL.Text,
    'species' : IDL.Text,
    'location' : IDL.Text,
    'photos' : IDL.Vec(IDL.Text),
    'vaccinationStatus' : IDL.Text,
    'shelterPhone' : IDL.Text,
  });
  const AdoptionApplication = IDL.Record({
    'id' : IDL.Text,
    'zip' : IDL.Text,
    'applicantName' : IDL.Text,
    'homeType' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'experience' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'petId' : IDL.Nat,
    'phone' : IDL.Text,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    'applyToFoster' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getBlogArticle' : IDL.Func([IDL.Nat], [IDL.Opt(BlogArticle)], ['query']),
    'getFeaturedPets' : IDL.Func([], [IDL.Vec(Pet)], ['query']),
    'getPet' : IDL.Func([IDL.Nat], [IDL.Opt(Pet)], ['query']),
    'listAdoptionApplications' : IDL.Func(
        [],
        [IDL.Vec(AdoptionApplication)],
        [],
      ),
    'listBlogArticles' : IDL.Func([], [IDL.Vec(BlogArticle)], ['query']),
    'listPets' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(Pet)],
        ['query'],
      ),
    'registerVolunteer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Text],
        [],
      ),
    'sendContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'setAdmin' : IDL.Func([], [IDL.Text], []),
    'submitAdoptionApplication' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };