/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdoptionApplication {
  'id' : string,
  'zip' : string,
  'applicantName' : string,
  'homeType' : string,
  'city' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'experience' : string,
  'state' : string,
  'address' : string,
  'petId' : bigint,
  'phone' : string,
  'reason' : string,
}
export interface BlogArticle {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishDate' : Timestamp,
  'tags' : Array<string>,
  'author' : string,
  'readTime' : string,
  'imageUrl' : string,
  'excerpt' : string,
}
export interface Pet {
  'id' : bigint,
  'age' : bigint,
  'name' : string,
  'description' : string,
  'shelterName' : string,
  'healthStatus' : string,
  'available' : boolean,
  'gender' : string,
  'shelterId' : string,
  'shelterEmail' : string,
  'breed' : string,
  'species' : string,
  'location' : string,
  'photos' : Array<string>,
  'vaccinationStatus' : string,
  'shelterPhone' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'applyToFoster' : ActorMethod<
    [string, string, string, string, string, string, string],
    string
  >,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getBlogArticle' : ActorMethod<[bigint], [] | [BlogArticle]>,
  'getFeaturedPets' : ActorMethod<[], Array<Pet>>,
  'getPet' : ActorMethod<[bigint], [] | [Pet]>,
  'listAdoptionApplications' : ActorMethod<[], Array<AdoptionApplication>>,
  'listBlogArticles' : ActorMethod<[], Array<BlogArticle>>,
  'listPets' : ActorMethod<
    [[] | [string], [] | [bigint], [] | [bigint], [] | [string], [] | [string]],
    Array<Pet>
  >,
  'registerVolunteer' : ActorMethod<
    [string, string, string, Array<string>, string],
    string
  >,
  'sendContactMessage' : ActorMethod<[string, string, string, string], string>,
  'setAdmin' : ActorMethod<[], string>,
  'submitAdoptionApplication' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];