/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Pet {
    id: bigint;
    age: bigint;
    name: string;
    description: string;
    shelterName: string;
    healthStatus: string;
    available: boolean;
    gender: string;
    shelterId: string;
    shelterEmail: string;
    breed: string;
    species: string;
    location: string;
    photos: Array<string>;
    vaccinationStatus: string;
    shelterPhone: string;
}
export interface AdoptionApplication {
    id: string;
    zip: string;
    applicantName: string;
    homeType: string;
    city: string;
    createdAt: Timestamp;
    email: string;
    experience: string;
    state: string;
    address: string;
    petId: bigint;
    phone: string;
    reason: string;
}
export interface BlogArticle {
    id: bigint;
    title: string;
    content: string;
    publishDate: Timestamp;
    tags: Array<string>;
    author: string;
    readTime: string;
    imageUrl: string;
    excerpt: string;
}
export interface backendInterface {
    applyToFoster(name: string, email: string, phone: string, homeType: string, experience: string, petType: string, duration: string): Promise<string>;
    getAdminPrincipal(): Promise<Principal | null>;
    getBlogArticle(id: bigint): Promise<BlogArticle | null>;
    getFeaturedPets(): Promise<Array<Pet>>;
    getPet(id: bigint): Promise<Pet | null>;
    listAdoptionApplications(): Promise<Array<AdoptionApplication>>;
    listBlogArticles(): Promise<Array<BlogArticle>>;
    listPets(species: string | null, ageMin: bigint | null, ageMax: bigint | null, breed: string | null, location: string | null): Promise<Array<Pet>>;
    registerVolunteer(name: string, email: string, phone: string, availability: Array<string>, interest: string): Promise<string>;
    sendContactMessage(name: string, email: string, subject: string, message: string): Promise<string>;
    setAdmin(): Promise<string>;
    submitAdoptionApplication(petId: bigint, applicantName: string, email: string, phone: string, address: string, city: string, state: string, zip: string, experience: string, homeType: string, reason: string): Promise<string>;
}
import type { BlogArticle as _BlogArticle, Pet as _Pet } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyToFoster(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToFoster(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToFoster(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogArticle(arg0: bigint): Promise<BlogArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogArticle(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogArticle(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedPets(): Promise<Array<Pet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedPets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedPets();
            return result;
        }
    }
    async getPet(arg0: bigint): Promise<Pet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPet(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPet(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAdoptionApplications(): Promise<Array<AdoptionApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdoptionApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdoptionApplications();
            return result;
        }
    }
    async listBlogArticles(): Promise<Array<BlogArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBlogArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBlogArticles();
            return result;
        }
    }
    async listPets(arg0: string | null, arg1: bigint | null, arg2: bigint | null, arg3: string | null, arg4: string | null): Promise<Array<Pet>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPets(to_candid_opt_n4(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPets(to_candid_opt_n4(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async registerVolunteer(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVolunteer(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVolunteer(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async sendContactMessage(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendContactMessage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendContactMessage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setAdmin(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin();
            return result;
        }
    }
    async submitAdoptionApplication(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAdoptionApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAdoptionApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogArticle]): BlogArticle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Pet]): Pet | null {
    return value.length === 0 ? null : value[0];
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
